In [4]:
import numpy as np
a=np.random.rand(3,2,2)
print a
print a[:]
print a[2,...]

[[[0.60391753 0.18931447]
  [0.76292725 0.35540197]]

 [[0.69325796 0.27977536]
  [0.25286935 0.13519635]]

 [[0.50726361 0.8914573 ]
  [0.06164101 0.87683678]]]
[[[0.60391753 0.18931447]
  [0.76292725 0.35540197]]

 [[0.69325796 0.27977536]
  [0.25286935 0.13519635]]

 [[0.50726361 0.8914573 ]
  [0.06164101 0.87683678]]]
[[0.50726361 0.8914573 ]
 [0.06164101 0.87683678]]


In [5]:
print len(a)

3


In [9]:
a=[1, 2,3 ,4, 5, 6, 7 ,8 ,9 ,10]
for i in range(2,5):
    print i
    #print a[i]
print '\n'
print a[:3]

2
3
4


[1, 2, 3]


In [12]:
import numpy as np
a=[0 for i in range(3)]
a[1]=[3,4]
a[0]=[1,2]
a[2]=[5,6]
a=np.array(a)
print a
print a.shape
print a.shape[1]

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
